language: node_js
node_js:
  - "lts/*"
cache: npm
script:
  - npm run build-client
  - npm run build-server
deploy:
  provider: releases
  api_key:
    secure: fCW6Jezgjcp3QSn6OPvPgZ8QT9iAAbPvTkCUIa8JHu8xJoHUUPZQI9SI78VPHwXaf0422Td3E04mfu0mwpxd9JunH524gotFDjGxYo0ccX17PeCp/9ticHWwXLcuITTdH9C4joUk1CAtjZHmyqq5kNenzkIdydBUehY3bKuUsrADtm0ZpRm417JVy09fwciWMQiLABGOxjAw0ZNtbZScgzo5ObZW3Yn+GBmqrYLKFmY1VZ3UGGvt+o4MvTPfuaQChiMBShNJVz0GE/WdGG+4TMnnKER2Z9GqTkCvHC3qL2E2RifpMNuar/5fuHFOmRriGuWSTN9ea4/odYt5PmHA9tyK5Ww/SQOzDwbbeZi/U5W/seaAe/rljFFSOgF3/rWiNkxEHnSGmWCF97PUfc8KtAMGELrdEntU6NWCcz5hyrtUrQg4kKykjNCrhdXt8N3EY4WvzMw8pQyo4FjplJf9dYJKLmvynvrH3VApVrqtfV2WdtLo6h7mJIvwUMU6HmJ3Wkc5loNeXrTSjK3/wkbIQ6lG9Wj4hlR2ZD0o2AiBzxOzsGHa2COsanoe7mvM7cZU/7NN053DQ2AGXL80+VeuS4xzwXg07MP8Rk2tmuDmaxn5ymW/spIwMTuGFqJt3aaVqoMHl17mQLghK1JlJ8SG5Is8Ys7U5cxhGY6F4uXLK0A=
  skip_cleanup: true
  on:
    tags: true
  file_glob: true
  file: dist/*
